name: example
description: An example app.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.0.0
dependencies:
  animation_player:
    path: ../
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  progress_animation_builder: '>=1.0.0 <3.0.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

