name: animation_player
description: Animation player.
version: 1.2.0+2
homepage: https://github.com/mono0926/animation_player
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  progress_animation_builder: ^1.0.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: